define({
  "_widgetLabel": "Katman Listesi",
  "titleBasemap": "Altlık haritaları",
  "titleLayers": "Operasyonel katmanlar",
  "labelLayer": "Katman adı",
  "itemZoomTo": "Şuna Yakınlaştır",
  "itemTransparency": "Saydamlık",
  "itemSetVisibilityRange": "Görünürlük aralığını ayarla",
  "itemTransparent": "Saydam",
  "itemOpaque": "Opak",
  "itemMoveUp": "Yukarı taşı",
  "itemMoveDown": "Aşağı taşı",
  "itemDesc": "Açıklama",
  "itemDownload": "İndir",
  "itemToAttributeTable": "Öznitelik Tablosunda Görüntüle",
  "itemShowItemDetails": "Öğe ayrıntılarını göster",
  "empty": "boş",
  "removePopup": "Açılır pencereleri devre dışı bırak",
  "enablePopup": "Açılan pencereyi etkinleştir",
  "turnAllLayersOff": "Tüm katmanları kapat",
  "turnAllLayersOn": "Tüm katmanları aç",
  "expandAllLayers": "Tüm katmanları genişlet",
  "collapseAlllayers": "Tüm katmanları daralt",
  "turnAllLabelsOff": "Tüm etiketleri kapat",
  "turnAllLabelsOn": "Tüm etiketleri aç",
  "showLabels": "Etiketleri göster",
  "hideLables": "Etiketleri gizle",
  "keyword": "Anahtar Kelime",
  "basemapLayers": "Altlık haritası katmanları",
  "typeAKeywork": "Bir anahtar kelime yazın",
  "layers": "Katmanlar"
});