define({
  "_widgetLabel": "लेयर सूची",
  "titleBasemap": "बेसमैप",
  "titleLayers": "ऑपरेशनल लेयर्स",
  "labelLayer": "लेयर का नाम",
  "itemZoomTo": "जूम करें",
  "itemTransparency": "पारदर्शिता",
  "itemSetVisibilityRange": "दृश्यता सीमा सेट करें",
  "itemTransparent": "पारदर्शी",
  "itemOpaque": "अपारदर्शी",
  "itemMoveUp": "ऊपर जाएँ",
  "itemMoveDown": "नीचे जाएँ",
  "itemDesc": "विवरण",
  "itemDownload": "डाउनलोड करें",
  "itemToAttributeTable": "विशेषता तालिका में दिखाएँ",
  "itemShowItemDetails": "आइटम के विवरण दिखाएं",
  "empty": "खाली",
  "removePopup": "पॉप-अप अक्षम करें",
  "enablePopup": "पॉप-अप सक्षम करें",
  "turnAllLayersOff": "सभी लेयरों को बंद करें",
  "turnAllLayersOn": "सभी लेयरों को चालू करें",
  "expandAllLayers": "सभी सीमाओं का विस्तार करें",
  "collapseAlllayers": "सभी लेयरों को संकुचित करें",
  "turnAllLabelsOff": "सभी लेबल को बंद करें",
  "turnAllLabelsOn": "सभी लेबल को चालू करें",
  "showLabels": "लेबल दिखाएं",
  "hideLables": "लेबल छिपाएँ",
  "keyword": "कीवर्ड",
  "basemapLayers": "बेसमैप लेयर्स",
  "typeAKeywork": "कोई कीवर्ड लिखें",
  "layers": "लेयर"
});