define({
  "_widgetLabel": "Λίστα θεματικών επιπέδων",
  "titleBasemap": "Υπόβαθρα",
  "titleLayers": "Επιχειρησιακά Επίπεδα",
  "labelLayer": "Όνομα θεματικού επιπέδου",
  "itemZoomTo": "Εστίαση",
  "itemTransparency": "Διαφάνεια",
  "itemSetVisibilityRange": "Καθορισμός εύρους τιμών ορατότητας",
  "itemTransparent": "Διαφανές",
  "itemOpaque": "Αδιαφανές",
  "itemMoveUp": "Μετακίνηση προς τα επάνω",
  "itemMoveDown": "Μετακίνηση προς τα κάτω",
  "itemDesc": "Περιγραφή",
  "itemDownload": "Λήψη",
  "itemToAttributeTable": "Προβολή στον πίνακα περιγραφικών γνωρισμάτων",
  "itemShowItemDetails": "Εμφάνιση λεπτομερειών αντικειμένου",
  "empty": "κενό",
  "removePopup": "Απενεργοποίηση αναδυόμενου παραθύρου",
  "enablePopup": "Ενεργοποίηση αναδυόμενου παραθύρου",
  "turnAllLayersOff": "Απενεργοποίηση όλων των θεματικών επιπέδων",
  "turnAllLayersOn": "Ενεργοποίηση όλων των θεματικών επιπέδων",
  "expandAllLayers": "Ανάπτυξη όλων των θεματικών επιπέδων",
  "collapseAlllayers": "Σύμπτυξη όλων των θεματικών επιπέδων",
  "turnAllLabelsOff": "Απενεργοποίηση όλων των ετικετών",
  "turnAllLabelsOn": "Ενεργοποίηση όλων των ετικετών",
  "showLabels": "Εμφάνιση ετικετών",
  "hideLables": "Απόκρυψη ετικετών",
  "keyword": "Λέξη-κλειδί",
  "basemapLayers": "Θεματικά επίπεδα υποβάθρου",
  "typeAKeywork": "Πληκτρολογήστε μια λέξη-κλειδί.",
  "layers": "Θεμ. επίπ."
});