define({
  "_widgetLabel": "Список слоев",
  "titleBasemap": "Базовые карты",
  "titleLayers": "Рабочие слои",
  "labelLayer": "Имя слоя",
  "itemZoomTo": "Приблизить к",
  "itemTransparency": "Прозрачность",
  "itemSetVisibilityRange": "Задать диапазон видимости",
  "itemTransparent": "Прозрачный",
  "itemOpaque": "Непрозрачный",
  "itemMoveUp": "Выше",
  "itemMoveDown": "Ниже",
  "itemDesc": "Описание",
  "itemDownload": "Загрузить",
  "itemToAttributeTable": "Просмотреть в таблице атрибутов",
  "itemShowItemDetails": "Показать информацию об элементе",
  "empty": "пусто",
  "removePopup": "Отключить всплывающее окно",
  "enablePopup": "Включить всплывающее окно",
  "turnAllLayersOff": "Выключить все слои",
  "turnAllLayersOn": "Включить все слои",
  "expandAllLayers": "Раскрыть все слои",
  "collapseAlllayers": "Свернуть все слои",
  "turnAllLabelsOff": "Выключить все надписи",
  "turnAllLabelsOn": "Включить все надписи",
  "showLabels": "Показать подписи",
  "hideLables": "Скрыть надписи",
  "keyword": "Ключевое слово",
  "basemapLayers": "Слои базовой карты",
  "typeAKeywork": "Введите ключевое слово",
  "layers": "Слои"
});